### ISSUE TITLE
ASDF integration?

### ISSUE THREAD

**Issue by guicho271828** [tani/papyrus#2]
Allowing X.l.md directly loadable from ASDF would be an interesting direction.

**Comment by guicho271828** [comment]
Sorry I missed the second part of the readme. It was obviously implemented.

**Comment by tani** [comment]
O.K. However I want to remove ".l" in :lmd of ASDF. Currently, Lambda requires to use ".l" like ;
    
    (:lmd "tutorial.l")

Do you have any idea?

**Comment by guicho271828** [comment]
you can just recommend a simple ".md" extension in the readme. Or you can use another extension like ".lmd". It may affect the source code highlightation by editors, but it is a matter of emacs/vim configuration which you can help simply by adding a source code snippet for `.emacs` (analogously for vim).

**Comment by tani** [comment]
Thank you for your advice.
I change it to the extension you said and also the project name too because of naming from the extension.
